#!/usr/bin/bash
sudo ufw status verbose
sudo apt-get install ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw allow 80/tcp
sudo ufw allow 8080/tcp
sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
sudo iptables-save > /etc/iptables/rules.v4
sudo ufw enable
sudo ufw status verbose
